# -Dspring.profiles.active=local
server:
  port: 37080
spring:
  application:
    name: issueMoaLearning
  config:
    import: optional:configserver:http://192.168.0.31:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh
eureka:
  instance:
    preferIpAddress: true # 서비스 이름 대신 서비스 IP 주소 등록
  client:
    registerWithEureka: true # 유레카 서비스 등록 여부 (default: true)
    fetchRegistry: true # 레지스트리 사본을 로컬에 내려받기 (default: true)
    serviceUrl:
      defaultZone: http://localhost:38761/eureka # 유레카 서비스의 위치 설정

endpoint:
  users:
    info: http://192.168.0.31:17070/users/info

springdoc:
  api-docs:
    path: /learning/v3/api-docs
  swagger-ui:
    path: /learning/swagger-ui.html